config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/new', to: 'users#new'
  put '/users', to: 'users#create'

  root to: "users#index"
  resources :users, :only => [:index, :destroy] do
    resources :shouts
  end

  get 'users/:user_id/followers', to: 'users#followers', as: 'user_followers'
  put 'users/:user_id/followers', to: 'users#follow', as: 'add_new_follower'
  delete 'users/:user_id/followers', to: 'users#unfollow', as: 'delete_follower'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shouts

  has_many :relationships, foreign_key: "follower_id"
  has_many :following, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name: "Relationship"
  has_many :followers, through: :reverse_relationships, source: :follower

  validates :username, presence: true, uniqueness: true
            # format: { with: /[a-zA-Z0-9]{4,20}/, message: "Must be between 4 and 20 alphanumerics." }
  validates :password, presence: true
  validates :email, presence: true

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(user)
    self.following.where("relationships.followed_id" => user.id).destroy!
  end

  def follows?(user)
    self.following.include?(user)
  end
end

app/controllers/UsersController.rb
class UsersController < ApplicationController

def new
 @user = User.new
 render :new
end

def create
@user = User.create(user_params)
redirect_to users_path, notice: "User Created."
end

def index
@users = User.all
render :index
end

def destroy
@user = User.find(params[:id])
@user.destroy
redirect_to users_path, notice: "User deleted."
end

private
def user_params
params.require(:user).permit(:username, :password)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_sign_up_params, if: :devise_controller?

  private
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_action :set_shout, only: [:destroy, :show, :update]
  before_action :set_user
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :redirect_unless_user_match, :except => [:show, :index]

  def index
    @shouts = @user.shouts.all
  end

  def new
    @shout = Shout.new
    render :new
  end

  def create
    @shout = Shout.new(shout_params)
    @shout.user_id = params[:user_id]
    @shout.save
    redirect_to user_shouts_path
  end

  def destroy
    @shout.destroy
    redirect_to :action => :index, notice: 'Shout destroyed.  Boo yah!'
  end

  def show
    @shout = Shout.find(params[:id])
    render :show
  end

  def update
    @shout.update(shout_params)
    @shout.save
    redirect_user users_shouts_path(@user, @shouts)
  end


  private

    def shout_params
      params.require(:shout).permit(:body, :user_id)
    end

    def set_shout
      @shout = Shout.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def redirect_unless_user_match
      unless @user == current_user
        flash[:notice] = "You cannot perform actions on #{@user.username}"
        redirect_to :root
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, :only => [:destroy]

  def new
   @user = User.new
   render :new
  end

  def create
    @user = User.create(user_params)
    redirect_to new_user_session
  end

  def index
    @users = User.all
    render :index
  end

  def destroy
    @user = User.find(params[:id])
    if current_user && (current_user.admin? || current_user == @user)
      @user.destroy
      redirect_to users_path, notice: "User deleted."
    else
      flash[:alert] = "You can only delete your own account!"
      redirect_to :root
    end
  end

private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouthouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% end %>

<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/shouts/_form.html.erb
<%= form_for([@user, @shout]) do |f| %>

  <div class="field">
    <%= f.label 'Body'%><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shouts/edit.html.erb
<h1>Editing Shout</h1>

<%= render 'form' %>

app/views/shouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Shouts</h1>

<% @user.shouts.each do |shouts| %>
  <div class="shout">
    <%= shouts.body %> | <%= link_to 'Delete', user_shout_path(@user, shouts), method: :delete %>

  </div>
<% end %>

<br>
---------------------
<p><%= link_to 'New Shout', new_user_shout_path(@user) %></p>

---------------------
<p><%= link_to 'Users Page', users_path(@user) %></p>

---------------------

app/views/shouts/new.html.erb
<h1>Create a new Shout</h1>

<%= render 'form' %>

<%= link_to 'Back', user_shouts_path %>

app/views/shouts/show.html.erb
<p class="notice"><%= notice %></p>

<% render "shout", shout: @shout %>

<% link_to 'Back', user_shouts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">

    <%= f.label 'Username' %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
   <%= f.label 'Password' %>
   <%= f.password_field :password %>

   </div>
   <div class="actions">
    <%= f.submit %>

  </div>
  <% end %>

app/views/users/follow.html.erb
<h1><%=current_user.username %>, here are some people to follow: </h1>

<br>

<li><%= @users.each do |user| %></li>
<li><%= link_to 'Follow', add_new_follower_path(user) %>

<%end%>

app/views/users/followers.html.erb
<h1><%=current_user.username %>, these are your followers: </h1>

<br>

<ul>
  <% current_user.followers.each do |f| %>
  <li> <%= f.username %> ; <%= f.email %> </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<P id="notice"><% notice %></p>
 <h1> Welcome!</h1>

  <ul>
      <% @users.each do |user| %>
      <li> Heya, <%= user.username %> </li>
      <li> <%= link_to "Shouts", user_shouts_path(user) %>
       <%= link_to "Delete User", user_path(user), method: :delete %>
       <%= link_to 'Followers', user_followers_path(user) %>
       <%= link_to 'Follow Another User', add_new_follower_path(user) %>
       </li>
       <% end %>
  </ul>

  <%= link_to 'New User', new_user_registration_path %>
<br>
---------------
<br>
  <%= link_to 'Sign In', new_user_session_path %>

app/views/users/new.html.erb
<!-- <h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %> -->

<h1> Sign Up </h1>

<%- form_for @user do |f| %>

  <div class="field">
    <%= f.label "Username"%>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label "Password " %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label "Email"%>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<%end%>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>

 <p>
   <strong>Username:</strong>
    <%= @user.username %>
    </p>

    <%= link_to 'Back', users_path %>